sudo: required
language: python
python:
  - "3.6"

os:
  - linux

before_install:
  - pip3 install --upgrade pip

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - flake8 galacteek
  - python setup.py build install
  - python setup.py sdist bdist_wheel

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd AppImage; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash -xe galacteek-appimage-build; fi
  - wget https://github.com/probonopd/uploadtool/raw/master/upload.sh

after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo "AppImage build successfull"; fi

branches:
  except:
    - devel
