sudo: required
dist: xenial
language: generic

os:
  - linux
  - osx

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash -xe travis/bootstrap-xenial.sh; fi

install:
  - bash -xe travis/install.sh

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then bash -xe travis/build-dmg.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd AppImage; bash -xe galacteek-appimage-build; cd ..; fi
  - wget https://github.com/probonopd/uploadtool/raw/master/upload.sh

after_success:
  - bash -xe travis/upload-images.sh

branches:
  except:
    - /^(?i:continuous)$/
