envs:
  default:
    widgets:
      gToolButton:
        defaultIconSize: 16

      gMediumToolButton:
        defaultIconSize: 24
      gSmallToolButton:
        defaultIconSize: 16
      gLargeToolButton:
        defaultIconSize: 32
